#!/usr/bin/env bash
#transfering of files from the client to the server.

FILE=$1
IP=$2
USER=$3
KEY=$4

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
