#!/usr/bin/env bash
# using sed to replace content in the nginx server

sudo apt update
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
