#!/usr/bin/env bash
#Configure your Nginx server

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/emmaculate-exceel permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

# Error404 Handling
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str1="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str1/" /etc/nginx/sites-enabled/default

sudo service nginx restart
