#!/usr/bin/env bash
# Error_404 page or page not found

sudo apt update
sudo apt install nginx -y

echo "Hello World!' | sudo tee /var/www/html/index.html

string="server_name _;\n\trewrite ^\/redirect_me https://github.com\/emmaculate-exceel permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est une page" | sudo tee /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/%new_str/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart