#!/usr/bin/env bash
# Error_404 page or page not found

sudo apt update
sudo apt install nginx -y

echo "Hello World!' | sudo tee /var/www/html/index.html"

string="server_name _;\n\trewrite ^\/redirect_me https://github.com\/emmaculate-exceel permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est une page" | sudo tee /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/%new_str/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart



#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint (eg: redirect /redirect_me to https://blog.ehoneahobed.com)
echo "Hello World!" | sudo tee /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/emmaculate-exceel permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

# Error404 Handling
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
