#!/usr/bin/env bash
#configuring the load_balancer
#configuring HAProxy for web-01 and web-02

sudo apt update
sudo apt install haproxy -y

server_config=\
"
frontend e-servy_frontend
	 bind *:80
	 mode http
	 default_backend e-servy

backend  e-servy_backend
	 balance roundrobin
	 server 463393-web-01 35.174.207.123:80 check
	 server 463393-web-02 100.25.129.60:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart