#!/usr/bin/env bash
# ping a host network 5 times and if it fails return the name of
# file that calls the function 

if [ $# -eq 0 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi 
