#!/usr/bin/env bash
# tell a story of passwd
# in the /etc/passwd directory

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo"The user $f1 is part of the $f2 gang, lives in $f3 and rides $f4. $f5's place is protected by the passcode $f6, more info about the user here: $f7"
done < /etc/passwd

The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
