#!/usr/bin/env bash
# using awk

awk '{count[$1, $9]++} END {
  for (key in count) {
    split(key, parts, SUBSEP)
    printf "%5d %s %\n", count[key], parts[1], parts[2]
  }
}' access.log | sort -nr
