#!/usr/bin/env bash
# print a series of state using the switch case

i=1

while [ $i -le 20 ];
do
	echo "$i"
	case $i in
	
	    4)
		echo "bad luck from China"
		;;
	    9)
		echo "bad luck from Japan"
		;;
	    17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
