#!/usr/bin/env bash
#file checking
#using or imitating the file command in bash

data="$(file)"

if [ -e "$data" ];
then
	echo "school file exists"
	if [ -s "$data" ];
	then
		echo "school file is not empty"
	fi
	if [ -f "$data" ];
	then
		echo "school file is a regular file"
	else
		echo "school file is empty"
	fi
else
    echo "school file does not exist"
fi
