#!/usr/bin/env bash
#A script that configures
#an Ubuntu server on a Docker
# Check if the script is running inside Docker


cp /etc/hosts ~/hosts.new
echo "127.0.0.2    localhost" > ~/etc/hosts.new >/dev/null
echo "8.8.8.8    facebook.com" >> ~/etc/hosts.new >/dev/null
cp -f ~/hosts.new /etc/hosts
