#!/usr/bin/env bash
#A script that configures
#an Ubuntu server on a Docker

# Check if the script is running inside Docker
if [ -f "/.dockerenv" ]; then
    cp /etc/hosts ~/hosts.new
    echo "127.0.0.2 localhost" > ~/etc/hosts
    echo "8.8.8.8 facebook.com" >>  ~/etc/hosts
    cp -f ~/host.new /etc/hosts

else
    echo "This script is intended to run inside Docker. Exiting."
    exit
fi
