#!/usr/bin/env bash
#A script that configures
#an Ubuntu server on a Docker

# Check if the script is running inside Docker
if [ -f "/.dockerenv" ];
then
    #"Running inside Docker. Proceeding with configuration."
    #Modify the /etc/hosts to configure localhost and facebook.com
    cp /etc/hosts ~/hosts.new
    echo "127.0.0.2    localhost" > ~/hosts.new
    echo "8.8.8.8      facebook.com" >> ~/hosts.new
    cp -f ~/etc/hosts.new /etc/hosts.new

else
    echo "This script is intended to run inside Docker. Exiting."
    exit
fi

# Modify /etc/hosts to configure localhost and facebook.com
