#!/usr/bin/env bash
# Update user and port in nginx config files
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2 #sudo service apache2 stop #pkill apache2 
sudo -u nginx service nginx start #sudo -u nginx service nginx start
