#!/usr/bin/env bash
# Generate a new SSH key with 4096 bits and protected by the passphrase "betty"
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'
ssh-keygen -lf ~/.ssh/school.pub
ssh-keygen -lv -f ~/.ssh/school.pub
